version: '3'
services:
  front:
    build: ./
    container_name: node
    volumes:
      - ./front:/front
    working_dir: /front
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true